name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_path: ./build/windows/x86_64/release/
            artifact_name: my-app
          - os: macos-latest
            build_path: ./build/macosx/x86_64/release/
            artifact_name: my-app
          - os: ubuntu-latest
            build_path: ./build/linux/x86_64/release/
            artifact_name: my-app
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Run Xmake Build
        run: xmake build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}/${{ matrix.artifact_name }}
